print( 'her name is zahra \n she is 32')
print('=' *40)
print( 'her name is zahre \r she is 32')
print('=' *40)
print( 'her name is zahre \a she is 32')
print('=' *40)
print( 'her name is zahre \b she is 32')
print('=' *40)
print( 'her name is zahre \t she is 32')
print('=' *40)
print( 'her name is zahre \f she is 32')
print('=' *40)
print( 'her name is zahre \v she is 32')
print('=' *40)
print( 'her name is zahre \" she is 32')
print('=' *40)
print( 'her name is zahre " she is 32 ')
print('=' *40)
print( 'her name is zahre \\ she is 32')
